# Use the official Ubuntu image

FROM ubuntu:latest

# copy the executable file

COPY sample_executable /SwengProject/sample_executable

# lounch the executable

CMD ["/SwengProject/sample_executable"]


